version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=dino_django_db
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"
  web:
    build: ./
    command: python manage.py runserver
    container_name: django_web
    volumes:
      - .:/dino
    ports:
      - "8000:8000"
    depends_on:
      - db
  app:
    build: ./
    command: python cars_movement.py
    container_name: cars
    volumes:
      - .:/dino
    depends_on:
      - db