# Generated by Django 4.2.1 on 2023-05-27 17:49

import delivery.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True, validators=[delivery.models.car_number_validator], verbose_name='Номер')),
                ('location', models.IntegerField(verbose_name='Локация')),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Грузоподъемность')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.IntegerField(verbose_name='Pick-up')),
                ('delivery_location', models.IntegerField(verbose_name='Delivery')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Вес')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('state', models.CharField(max_length=255, verbose_name='Штат')),
                ('postal_code', models.IntegerField(unique=True, verbose_name='Почтовый индекс')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локации',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
